### ISSUE TITLE
Transcoder mpd is always configured for livestream

### ISSUE THREAD

**Issue by niklasstich** [HSKE-Streaming-Server/media-streaming-server#13]
We have to implement a switch to change the mpd behaviour from livestream to video, see https://github.com/HSKE-Streaming-Server/media-streaming-client/issues/6

**Comment by AlexanderWalk** [comment]
Das Verhalten bleibt im Prinzip immer gleich.

Es wird beim Transcodieren ein Maximum an Segmenten in der .mpd Datei festgelegt (-window_size Wert in FFMPEG)
Für jedes Segment über diesem Limit, wird das Älteste aus der Playlist entfernt. Das heißt, dass man beim Starten des Videos immer an der ältesten, verfügbaren Stelle eintritt.
Der Wert muss so hoh angesetzt werden, dass jedes Segment in der Playlist-Datei referenziert werden kann, um das ganze Video von Anfang an abspielen zu können.

**Comment by niklasstich** [comment]
Wird gefixed im Client von @h-fares, indem wir einen Switch einbauen, sodass bei einem Video das Autoplay konfiguriert und abgewartet wird, das Video beginnt dann von vorne.
