### ISSUE TITLE
Grabber.cs tries to load the 'ImageLocation' which is NULL

### ISSUE THREAD

**Issue by DominikWiesner** [HSKE-Streaming-Server/media-streaming-server#14]
If the ImageLocation in the database is NULL, the Grabber.cs tries to load in in Line 90 anyway and crashes

**Comment by niklasstich** [comment]
Fixed with https://github.com/HSKE-Streaming-Server/media-streaming-server/commit/ca4313d57ce2f1482e86bba39b39dd0b9e6e186c

**Comment by DominikWiesner** [comment]
Solved: https://github.com/HSKE-Streaming-Server/media-streaming-server/commit/e2bd1d57e315266f8b151677b5cf301bdc9c36a1
