### ISSUE TITLE
Video- und Audiopreset bei Request immer 0

### ISSUE THREAD

**Issue by AlexanderWalk** [HSKE-Streaming-Server/media-streaming-server#17]
Egal was im Client eingestellt wird, beim Request kommen im MainController immer der Wert 0 bei Video- und Audiopreset an.

**Comment by FlorianBirk** [comment]
![image](https://user-images.githubusercontent.com/34124307/82921731-fe538600-9f78-11ea-8496-42feea528733.png)

fixed mit HSKE-Streaming-Server/media-streaming-client@5da5dd03d11cdd0925d4400939db86a56f56abbc
