### ISSUE TITLE
Keepalive wird nicht respektiert

### ISSUE THREAD

**Issue by niklasstich** [HSKE-Streaming-Server/media-streaming-server#23]
Die Keepalives, die vom Client gesendet werden, werden nicht vom Server respektiert. Debuggen und testen.

**Comment by niklasstich** [comment]
@AlexanderWalk Müssen wir [hier](https://github.com/HSKE-Streaming-Server/media-streaming-server/blob/9c7e768d72ed53dac9b0f2dd98cb1395aeaac30a/API/Manager/ServerManager.cs#L104) unbedingt die Presets nochmal abchecken? Eigentlich ist das doch durch die URI der Playlist schon eindeutig, da diese ja unbedingt mit einem verwendeten Audio- und Videopreset zusammenhängt, oder sehe ich das falsch? Aktuell funktioniert das ganze daher nicht, weil der Client uns die falschen Presets schickt (bei mir momentan -1 und -1).

**Comment by AlexanderWalk** [comment]
Da hast du recht. Da die transcoded Uri gechecked wird, sind die presets bereits bestimmt.
